name: Build and deploy

on:
  push:
  workflow_dispatch:

env:
  DOTNET_SDK_VERSION: '9.0.x'
  DOTNET_TFM: 'net9.0'

jobs:
  build-and-test:
    runs-on: [self-hosted, gandalf]
    steps:
      - name: Deploy
        run: |
          cd /home/lassevk/Apps/EsoWatch
          git fetch
          git merge --ff-only

          /home/lassevk/.dotnet/dotnet build ./EsoWatch.sln

          sudo systemctl stop esowatch
          /home/lassevk/.dotnet/dotnet publish EsoWatch/EsoWatch.csproj -o ./run
          sudo systemctl start esowatch

          #pushover "EsoWatch Deployed"